version: "3.8"

services:
  app:
    build: .
    container_name: sudss-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
